// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SundryAndViceComfortStationSite.Migrations
{
    [DbContext(typeof(CircleHospitalityContext))]
    [Migration("20240516215626_Removed_Gal_Hours_LocationMenu")]
    partial class Removed_Gal_Hours_LocationMenu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ingredient", b =>
                {
                    b.Property<int>("IngredientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientID"));

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ItemIngredientIngredientID")
                        .HasColumnType("int");

                    b.Property<int?>("ItemIngredientMenuItemID")
                        .HasColumnType("int");

                    b.HasKey("IngredientID");

                    b.HasIndex("ItemIngredientMenuItemID", "ItemIngredientIngredientID");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("ItemIngredient", b =>
                {
                    b.Property<int>("MenuItemID")
                        .HasColumnType("int");

                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<int>("MeasurementID")
                        .HasColumnType("int");

                    b.HasKey("MenuItemID", "IngredientID");

                    b.HasIndex("IngredientID");

                    b.HasIndex("MeasurementID");

                    b.ToTable("ItemIngredients");
                });

            modelBuilder.Entity("ItemIngredientMenuItem", b =>
                {
                    b.Property<int>("MenuItemsMenuItemID")
                        .HasColumnType("int");

                    b.Property<int>("ItemIngredientsMenuItemID")
                        .HasColumnType("int");

                    b.Property<int>("ItemIngredientsIngredientID")
                        .HasColumnType("int");

                    b.HasKey("MenuItemsMenuItemID", "ItemIngredientsMenuItemID", "ItemIngredientsIngredientID");

                    b.HasIndex("ItemIngredientsMenuItemID", "ItemIngredientsIngredientID");

                    b.ToTable("ItemIngredientMenuItem");
                });

            modelBuilder.Entity("ItemType", b =>
                {
                    b.Property<int>("ItemTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemTypeID"));

                    b.Property<string>("ItemTypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemTypeID");

                    b.ToTable("ItemTypes");
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationID"));

                    b.Property<string>("LocationAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MenuItemID")
                        .HasColumnType("int");

                    b.HasKey("LocationID");

                    b.HasIndex("MenuItemID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Measurement", b =>
                {
                    b.Property<int>("MeasurementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeasurementID"));

                    b.Property<int?>("ItemIngredientIngredientID")
                        .HasColumnType("int");

                    b.Property<int?>("ItemIngredientMenuItemID")
                        .HasColumnType("int");

                    b.Property<string>("MeasurementDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MeasurementID");

                    b.HasIndex("ItemIngredientMenuItemID", "ItemIngredientIngredientID");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("MenuItem", b =>
                {
                    b.Property<int>("MenuItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemID"));

                    b.Property<string>("CreatorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemTypeID")
                        .HasColumnType("int");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.HasKey("MenuItemID");

                    b.HasIndex("ItemTypeID");

                    b.HasIndex("LocationID");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("Ingredient", b =>
                {
                    b.HasOne("ItemIngredient", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("ItemIngredientMenuItemID", "ItemIngredientIngredientID");
                });

            modelBuilder.Entity("ItemIngredient", b =>
                {
                    b.HasOne("Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("ItemIngredientMenuItem", b =>
                {
                    b.HasOne("MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemsMenuItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItemIngredient", null)
                        .WithMany()
                        .HasForeignKey("ItemIngredientsMenuItemID", "ItemIngredientsIngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.HasOne("MenuItem", null)
                        .WithMany("Locations")
                        .HasForeignKey("MenuItemID");
                });

            modelBuilder.Entity("Measurement", b =>
                {
                    b.HasOne("ItemIngredient", null)
                        .WithMany("Measurements")
                        .HasForeignKey("ItemIngredientMenuItemID", "ItemIngredientIngredientID");
                });

            modelBuilder.Entity("MenuItem", b =>
                {
                    b.HasOne("ItemType", "ItemType")
                        .WithMany("MenuItems")
                        .HasForeignKey("ItemTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemType");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ItemIngredient", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("ItemType", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("MenuItem", b =>
                {
                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
